### ISSUE TITLE
Update SDK version

### ISSUE THREAD

**Issue by roman-radchenko** [vladmikhbond/MvcChat#4]
Сейчас в проекте используется sdk версии: **1.0.0-preview2-003121**
А последняя [доступная](https://www.microsoft.com/net/core#windows) версия: **1.0.0-preview2-003133**
Хорошо бы всем синхронизироваться для дальнейшей работы, иначе:
![core_fail](https://cloud.githubusercontent.com/assets/22524478/18991305/4ba0875c-8720-11e6-8d7b-ed7d174f9e75.png)

global.json:

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003133"
  }
}
```

**Comment by vladmikhbond** [comment]
Да нет проблем.
Наиболее продвинутая версия находится в ветке volodymyr.
Я попробовал смержить ее с master, чтоб потом убить, но в результате только
попортил мастера.
В пн. надо еще попытаться )


30 сентября 2016 г., 15:13 пользователь Roman <notifications@github.com>
написал:
